### ISSUE TITLE
Repo license

### ISSUE THREAD

**Issue by elhanan-mishraky** [j2kun/segment#2]
Hi @j2kun, I'm thinking if making use of this code in another Apache-2 Open Source project. However, I couldn't find a license in the repo and I found out that if a repository has no license, then all rights are reserved and it is not Open Source or Free. Did you intend to allow free usage of the repo? If so will it be possible to add Apache-2 or similar license to the repo?

**Comment by j2kun** [comment]
Added the MIT license, which I think is permissive enough for Apache-2-licensed purposes. Please let me know if not and I can change it. Enjoy the code!
